### ISSUE TITLE
Mail with Html not worlink

### ISSUE THREAD

**Issue by john182** [codylerum/simple-email#1]
email not format html:

  EmailMessage email = new MailMessageImpl(getMailConfig(confEmail))
                .to(nfe.getDestinatario().getEmail())
                .subject(assunto)
                .bodyHtmlTextAlt(html,confEmail.getAssunto()).importance(MessagePriority.HIGH)
                .addAttachment(ContentDisposition.ATTACHMENT, new File(caminhoXml))
                .addAttachment(ContentDisposition.ATTACHMENT, new File(arquivoPdf))
                .send();

**Comment by codylerum** [comment]
Can you provide some more detail as to what you are experiencing?

FYI this project isn't actively maintained.

**Comment by john182** [comment]
email it's like text
https://screenshot.net/pt/nx37jcn

**Comment by kmix** [comment]
@john182 Is this still an issue for you with the current release? If so, do you have a reproducer I could take a quick look at?
